name: 'ubuntu-jammy (docker)'

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'README.md'
      - 'docker/ubuntu/README.md'
      - 'docker/INSTALL-SCRIPT'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/Checkout@v3

      - name: 'Docker upload'
        uses: how2flow/upload-docker-action@v1
        with:
          context: ./docker/ubuntu/jammy
          repository: 'config'
          release: 'jammy'
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
